### PR TITLE
Text for HelloRetryRequest

### PR DESCRIPTION
**Pull request by hannestschofenig**

### CODE REVIEW

**Comment by martinthomson** [comment]
Do you really think that it is a good idea to encode HRR the same way as we did in TLS 1.3?  We're relying on signaling in the ServerHello.random where we don't really need to.  Worse, we're entertaining the possibility of making that field shorter, which makes this sort of signaling far more challenging as it removes space for real freshness.

We reserved the handshake type codepoint.  Would it be possible to use that?

**Comment by ekr** [comment]
Yes, that is the plan that Richard and I worked out offline.

**Comment by hannestschofenig** [comment]
I changed the text to include an optimized HRR, which is similar to what was in previous version of TLS 1.3 (without the special value encoded in the random and the extra fields for backwards compatibility).

**Comment by ekr** [comment]
merged by hand

**Pull request closed without merging**
